 package in.cdac.java.parameters;

public enum ResidentAuthenticationType {
   FINGERPRINT,
   IRIS,
   OTP,
   OTP_FINGERPRINT,
   OTP_IRIS,
   FINGERPRINT_IRIS,
   OTP_FINGERPRINT_IRIS,
   FACE,
   FINGERPRINT_FACE,
   IRIS_FACE,
   FACE_OTP,
   FINGERPRINT_FACE_OTP,
   IRIS_FACE_OTP,
   FINGERPRINT_IRIS_FACE,
   FINGERPRINT_IRIS_FACE_OTP;
}
    